CALL InserirCurso('Matemática', 'Ciências Exatas');
CALL InserirCurso('Física', 'Ciências Exatas');
CALL InserirCurso('Química', 'Ciências Exatas');
CALL InserirCurso('Biologia', 'Ciências Biológicas');
CALL InserirCurso('Medicina', 'Ciências da Saúde');
CALL InserirCurso('Enfermagem', 'Ciências da Saúde');
CALL InserirCurso('Direito', 'Ciências Humanas');
CALL InserirCurso('Psicologia', 'Ciências Humanas');
CALL InserirCurso('História', 'Ciências Humanas');
CALL InserirCurso('Geografia', 'Ciências Humanas');
CALL InserirCurso('Engenharia Civil', 'Engenharia');
CALL InserirCurso('Engenharia Mecânica', 'Engenharia');
CALL InserirCurso('Engenharia Elétrica', 'Engenharia');
CALL InserirCurso('Engenharia de Computação', 'Engenharia');
CALL InserirCurso('Ciência da Computação', 'Tecnologia');
CALL InserirCurso('Sistemas de Informação', 'Tecnologia');
CALL InserirCurso('Administração', 'Negócios');
CALL InserirCurso('Economia', 'Negócios');
CALL InserirCurso('Contabilidade', 'Negócios');
CALL InserirCurso('Marketing', 'Negócios');
CALL InserirCurso('Arquitetura', 'Artes');
CALL InserirCurso('Design Gráfico', 'Artes');
CALL InserirCurso('Música', 'Artes');
CALL InserirCurso('Educação Física', 'Educação');
CALL InserirCurso('Pedagogia', 'Educação');

CALL InserirAluno('João', 'Silva', 'Matemática', 'Ciências Exatas');
CALL InserirAluno('Maria', 'Souza', 'Física', 'Ciências Exatas');
CALL InserirAluno('Pedro', 'Oliveira', 'Química', 'Ciências Exatas');
CALL InserirAluno('Ana', 'Pereira', 'Biologia', 'Ciências Biológicas');
CALL InserirAluno('Lucas', 'Santos', 'Medicina', 'Ciências da Saúde');
CALL InserirAluno('Mariana', 'Lima', 'Enfermagem', 'Ciências da Saúde');
CALL InserirAluno('Carlos', 'Ferreira', 'Direito', 'Ciências Humanas');
CALL InserirAluno('Fernanda', 'Costa', 'Psicologia', 'Ciências Humanas');
CALL InserirAluno('Rafael', 'Rodrigues', 'História', 'Ciências Humanas');
CALL InserirAluno('Juliana', 'Martins', 'Geografia', 'Ciências Humanas');
CALL InserirAluno('Gustavo', 'Almeida', 'Engenharia Civil', 'Engenharia');
CALL InserirAluno('Beatriz', 'Barbosa', 'Engenharia Mecânica', 'Engenharia');
CALL InserirAluno('Felipe', 'Ribeiro', 'Engenharia Elétrica', 'Engenharia');
CALL InserirAluno('Larissa', 'Mendes', 'Engenharia de Computação', 'Engenharia');
CALL InserirAluno('Bruno', 'Gonçalves', 'Ciência da Computação', 'Tecnologia');
CALL InserirAluno('Camila', 'Carvalho', 'Sistemas de Informação', 'Tecnologia');
CALL InserirAluno('Thiago', 'Silveira', 'Administração', 'Negócios');
CALL InserirAluno('Patrícia', 'Azevedo', 'Economia', 'Negócios');
CALL InserirAluno('Ricardo', 'Teixeira', 'Contabilidade', 'Negócios');
CALL InserirAluno('Aline', 'Moreira', 'Marketing', 'Negócios');
CALL InserirAluno('Eduardo', 'Vieira', 'Arquitetura', 'Artes');
CALL InserirAluno('Vanessa', 'Cardoso', 'Design Gráfico', 'Artes');
CALL InserirAluno('Rodrigo', 'Rocha', 'Música', 'Artes');
CALL InserirAluno('Tatiana', 'Nunes', 'Educação Física', 'Educação');
CALL InserirAluno('André', 'Reis', 'Pedagogia', 'Educação');
CALL InserirAluno('Gabriel', 'Cunha', 'Matemática', 'Ciências Exatas');
CALL InserirAluno('Isabela', 'Duarte', 'Física', 'Ciências Exatas');
CALL InserirAluno('Leonardo', 'Freitas', 'Química', 'Ciências Exatas');
CALL InserirAluno('Sofia', 'Castro', 'Biologia', 'Ciências Biológicas');
CALL InserirAluno('Daniel', 'Moraes', 'Medicina', 'Ciências da Saúde');
CALL InserirAluno('Luana', 'Ramos', 'Enfermagem', 'Ciências da Saúde');
CALL InserirAluno('Marcelo', 'Pinto', 'Direito', 'Ciências Humanas');
CALL InserirAluno('Renata', 'Gomes', 'Psicologia', 'Ciências Humanas');
CALL InserirAluno('Alexandre', 'Sousa', 'História', 'Ciências Humanas');
CALL InserirAluno('Carolina', 'Lopes', 'Geografia', 'Ciências Humanas');
CALL InserirAluno('Vitor', 'Nascimento', 'Engenharia Civil', 'Engenharia');
CALL InserirAluno('Natália', 'Farias', 'Engenharia Mecânica', 'Engenharia');
CALL InserirAluno('Henrique', 'Monteiro', 'Engenharia Elétrica', 'Engenharia');
CALL InserirAluno('Paula', 'Cavalcanti', 'Engenharia de Computação', 'Engenharia');
CALL InserirAluno('Diego', 'Campos', 'Ciência da Computação', 'Tecnologia');
CALL InserirAluno('Letícia', 'Borges', 'Sistemas de Informação', 'Tecnologia');
CALL InserirAluno('Rogério', 'Guimarães', 'Administração', 'Negócios');
CALL InserirAluno('Simone', 'Tavares', 'Economia', 'Negócios');
CALL InserirAluno('Fábio', 'Macedo', 'Contabilidade', 'Negócios');
CALL InserirAluno('Elaine', 'Xavier', 'Marketing', 'Negócios');
CALL InserirAluno('Otávio', 'Pacheco', 'Arquitetura', 'Artes');
CALL InserirAluno('Viviane', 'Peixoto', 'Design Gráfico', 'Artes');
CALL InserirAluno('Maurício', 'Neves', 'Música', 'Artes');
CALL InserirAluno('Adriana', 'Siqueira', 'Educação Física', 'Educação');
CALL InserirAluno('Rafael', 'Amaral', 'Pedagogia', 'Educação');
CALL InserirAluno('Bruna', 'Martins', 'Matemática', 'Ciências Exatas');
CALL InserirAluno('Fernando', 'Oliveira', 'Física', 'Ciências Exatas');
CALL InserirAluno('Juliana', 'Silva', 'Química', 'Ciências Exatas');
CALL InserirAluno('Marcelo', 'Souza', 'Biologia', 'Ciências Biológicas');
CALL InserirAluno('Patrícia', 'Pereira', 'Medicina', 'Ciências da Saúde');
CALL InserirAluno('Rodrigo', 'Santos', 'Enfermagem', 'Ciências da Saúde');
CALL InserirAluno('Carla', 'Lima', 'Direito', 'Ciências Humanas');
CALL InserirAluno('Gustavo', 'Ferreira', 'Psicologia', 'Ciências Humanas');
CALL InserirAluno('Mariana', 'Costa', 'História', 'Ciências Humanas');
CALL InserirAluno('Felipe', 'Rodrigues', 'Geografia', 'Ciências Humanas');
CALL InserirAluno('Ana', 'Martins', 'Engenharia Civil', 'Engenharia');
CALL InserirAluno('Lucas', 'Almeida', 'Engenharia Mecânica', 'Engenharia');
CALL InserirAluno('Beatriz', 'Barbosa', 'Engenharia Elétrica', 'Engenharia');
CALL InserirAluno('Pedro', 'Ribeiro', 'Engenharia de Computação', 'Engenharia');
CALL InserirAluno('Larissa', 'Mendes', 'Ciência da Computação', 'Tecnologia');
CALL InserirAluno('Bruno', 'Gonçalves', 'Sistemas de Informação', 'Tecnologia');
CALL InserirAluno('Camila', 'Carvalho', 'Administração', 'Negócios');
CALL InserirAluno('Thiago', 'Silveira', 'Economia', 'Negócios');
CALL InserirAluno('Patrícia', 'Azevedo', 'Contabilidade', 'Negócios');
CALL InserirAluno('Ricardo', 'Teixeira', 'Marketing', 'Negócios');
CALL InserirAluno('Aline', 'Moreira', 'Arquitetura', 'Artes');
CALL InserirAluno('Eduardo', 'Vieira', 'Design Gráfico', 'Artes');
CALL InserirAluno('Vanessa', 'Cardoso', 'Música', 'Artes');
CALL InserirAluno('Rodrigo', 'Rocha', 'Educação Física', 'Educação');
CALL InserirAluno('Tatiana', 'Nunes', 'Pedagogia', 'Educação');
CALL InserirAluno('André', 'Reis', 'Matemática', 'Ciências Exatas');
CALL InserirAluno('Gabriel', 'Cunha', 'Física', 'Ciências Exatas');
CALL InserirAluno('Isabela', 'Duarte', 'Química', 'Ciências Exatas');
CALL InserirAluno('Leonardo', 'Freitas', 'Biologia', 'Ciências Biológicas');
CALL InserirAluno('Sofia', 'Castro', 'Medicina', 'Ciências da Saúde');
CALL InserirAluno('Daniel', 'Moraes', 'Enfermagem', 'Ciências da Saúde');
CALL InserirAluno('Luana', 'Ramos', 'Direito', 'Ciências Humanas');
CALL InserirAluno('Marcelo', 'Pinto', 'Psicologia', 'Ciências Humanas');
CALL InserirAluno('Renata', 'Gomes', 'História', 'Ciências Humanas');
CALL InserirAluno('Alexandre', 'Sousa', 'Geografia', 'Ciências Humanas');
CALL InserirAluno('Carolina', 'Lopes', 'Engenharia Civil', 'Engenharia');
CALL InserirAluno('Vitor', 'Nascimento', 'Engenharia Mecânica', 'Engenharia');
CALL InserirAluno('Natália', 'Farias', 'Engenharia Elétrica', 'Engenharia');
CALL InserirAluno('Henrique', 'Monteiro', 'Engenharia de Computação', 'Engenharia');
CALL InserirAluno('Paula', 'Cavalcanti', 'Ciência da Computação', 'Tecnologia');
CALL InserirAluno('Diego', 'Campos', 'Sistemas de Informação', 'Tecnologia');
CALL InserirAluno('Letícia', 'Borges', 'Sistemas de Informação', 'Tecnologia');
CALL InserirAluno('Rogério', 'Guimarães', 'Administração', 'Negócios');
CALL InserirAluno('Simone', 'Tavares', 'Economia', 'Negócios');
CALL InserirAluno('Fábio', 'Macedo', 'Contabilidade', 'Negócios');
CALL InserirAluno('Elaine', 'Xavier', 'Marketing', 'Negócios');
CALL InserirAluno('Otávio', 'Pacheco', 'Arquitetura', 'Artes');
CALL InserirAluno('Viviane', 'Peixoto', 'Design Gráfico', 'Artes');
CALL InserirAluno('Maurício', 'Neves', 'Música', 'Artes');
CALL InserirAluno('Adriana', 'Siqueira', 'Educação Física', 'Educação');
CALL InserirAluno('Rafael', 'Amaral', 'Pedagogia', 'Educação');
CALL InserirAluno('Bruna', 'Martins', 'Matemática', 'Ciências Exatas');
CALL InserirAluno('Fernando', 'Oliveira', 'Física', 'Ciências Exatas');
CALL InserirAluno('Juliana', 'Silva', 'Química', 'Ciências Exatas');
CALL InserirAluno('Marcelo', 'Souza', 'Biologia', 'Ciências Biológicas');
CALL InserirAluno('Patrícia', 'Pereira', 'Medicina', 'Ciências da Saúde');
CALL InserirAluno('Rodrigo', 'Santos', 'Enfermagem', 'Ciências da Saúde');
CALL InserirAluno('Carla', 'Lima', 'Direito', 'Ciências Humanas');
CALL InserirAluno('Gustavo', 'Ferreira', 'Psicologia', 'Ciências Humanas');
CALL InserirAluno('Mariana', 'Costa', 'História', 'Ciências Humanas');
CALL InserirAluno('Felipe', 'Rodrigues', 'Geografia', 'Ciências Humanas');
CALL InserirAluno('Ana', 'Martins', 'Engenharia Civil', 'Engenharia');
CALL InserirAluno('Lucas', 'Almeida', 'Engenharia Mecânica', 'Engenharia');
CALL InserirAluno('Beatriz', 'Barbosa', 'Engenharia Elétrica', 'Engenharia');
CALL InserirAluno('Pedro', 'Ribeiro', 'Engenharia de Computação', 'Engenharia');
CALL InserirAluno('Larissa', 'Mendes', 'Ciência da Computação', 'Tecnologia');
CALL InserirAluno('Bruno', 'Gonçalves', 'Sistemas de Informação', 'Tecnologia');
CALL InserirAluno('Camila', 'Carvalho', 'Administração', 'Negócios');
CALL InserirAluno('Thiago', 'Silveira', 'Economia', 'Negócios');
CALL InserirAluno('Patrícia', 'Azevedo', 'Contabilidade', 'Negócios');
CALL InserirAluno('Ricardo', 'Teixeira', 'Marketing', 'Negócios');
CALL InserirAluno('Aline', 'Moreira', 'Arquitetura', 'Artes');
CALL InserirAluno('Eduardo', 'Vieira', 'Design Gráfico', 'Artes');
CALL InserirAluno('Vanessa', 'Cardoso', 'Música', 'Artes');
CALL InserirAluno('Rodrigo', 'Rocha', 'Educação Física', 'Educação');
CALL InserirAluno('Tatiana', 'Nunes', 'Pedagogia', 'Educação');
CALL InserirAluno('André', 'Reis', 'Matemática', 'Ciências Exatas');
CALL InserirAluno('Gabriel', 'Cunha', 'Física', 'Ciências Exatas');
CALL InserirAluno('Isabela', 'Duarte', 'Química', 'Ciências Exatas');
CALL InserirAluno('Leonardo', 'Freitas', 'Biologia', 'Ciências Biológicas');
CALL InserirAluno('Sofia', 'Castro', 'Medicina', 'Ciências da Saúde');
CALL InserirAluno('Daniel', 'Moraes', 'Enfermagem', 'Ciências da Saúde');
CALL InserirAluno('Luana', 'Ramos', 'Direito', 'Ciências Humanas');
CALL InserirAluno('Marcelo', 'Pinto', 'Psicologia', 'Ciências Humanas');
CALL InserirAluno('Renata', 'Gomes', 'História', 'Ciências Humanas');
CALL InserirAluno('Alexandre', 'Sousa', 'Geografia', 'Ciências Humanas');
CALL InserirAluno('Carolina', 'Lopes', 'Engenharia Civil', 'Engenharia');
CALL InserirAluno('Vitor', 'Nascimento', 'Engenharia Mecânica', 'Engenharia');
CALL InserirAluno('Natália', 'Farias', 'Engenharia Elétrica', 'Engenharia');
CALL InserirAluno('Henrique', 'Monteiro', 'Engenharia de Computação', 'Engenharia');
CALL InserirAluno('Paula', 'Cavalcanti', 'Ciência da Computação', 'Tecnologia');
CALL InserirAluno('Diego', 'Campos', 'Sistemas de Informação', 'Tecnologia');
CALL InserirAluno('Letícia', 'Borges', 'Administração', 'Negócios');
CALL InserirAluno('Rogério', 'Guimarães', 'Economia', 'Negócios');
CALL InserirAluno('Simone', 'Tavares', 'Contabilidade', 'Negócios');
CALL InserirAluno('Fábio', 'Macedo', 'Marketing', 'Negócios');
CALL InserirAluno('Elaine', 'Xavier', 'Arquitetura', 'Artes');
CALL InserirAluno('Otávio', 'Pacheco', 'Design Gráfico', 'Artes');
CALL InserirAluno('Viviane', 'Peixoto', 'Música', 'Artes');
CALL InserirAluno('Maurício', 'Neves', 'Educação Física', 'Educação');
CALL InserirAluno('Adriana', 'Siqueira', 'Pedagogia', 'Educação');
CALL InserirAluno('Rafael', 'Amaral', 'Matemática', 'Ciências Exatas');
CALL InserirAluno('Bruna', 'Martins', 'Física', 'Ciências Exatas');
CALL InserirAluno('Fernando', 'Oliveira', 'Química', 'Ciências Exatas');
CALL InserirAluno('Juliana', 'Silva', 'Biologia', 'Ciências Biológicas');
CALL InserirAluno('Marcelo', 'Souza', 'Medicina', 'Ciências da Saúde');
CALL InserirAluno('Patrícia', 'Pereira', 'Enfermagem', 'Ciências da Saúde');
CALL InserirAluno('Rodrigo', 'Santos', 'Direito', 'Ciências Humanas');
CALL InserirAluno('Carla', 'Lima', 'Psicologia', 'Ciências Humanas');
CALL InserirAluno('Gustavo', 'Ferreira', 'História', 'Ciências Humanas');
CALL InserirAluno('Mariana', 'Costa', 'Geografia', 'Ciências Humanas');
CALL InserirAluno('Felipe', 'Rodrigues', 'Engenharia Civil', 'Engenharia');
CALL InserirAluno('Ana', 'Martins', 'Engenharia Mecânica', 'Engenharia');
CALL InserirAluno('Lucas', 'Almeida', 'Engenharia Elétrica', 'Engenharia');
CALL InserirAluno('Beatriz', 'Barbosa', 'Engenharia de Computação', 'Engenharia');
CALL InserirAluno('Pedro', 'Ribeiro', 'Ciência da Computação', 'Tecnologia');
CALL InserirAluno('Larissa', 'Mendes', 'Sistemas de Informação', 'Tecnologia');
CALL InserirAluno('Bruno', 'Gonçalves', 'Administração', 'Negócios');
CALL InserirAluno('Camila', 'Carvalho', 'Economia', 'Negócios');
CALL InserirAluno('Thiago', 'Silveira', 'Contabilidade', 'Negócios');
CALL InserirAluno('Patrícia', 'Azevedo', 'Marketing', 'Negócios');
CALL InserirAluno('Ricardo', 'Teixeira', 'Arquitetura', 'Artes');
CALL InserirAluno('Aline', 'Moreira', 'Design Gráfico', 'Artes');
CALL InserirAluno('Eduardo', 'Vieira', 'Música', 'Artes');
CALL InserirAluno('Vanessa', 'Cardoso', 'Educação Física', 'Educação');
CALL InserirAluno('Rodrigo', 'Rocha', 'Pedagogia', 'Educação');
CALL InserirAluno('Tatiana', 'Nunes', 'Matemática', 'Ciências Exatas');
CALL InserirAluno('André', 'Reis', 'Física', 'Ciências Exatas');
CALL InserirAluno('Gabriel', 'Cunha', 'Química', 'Ciências Exatas');
CALL InserirAluno('Isabela', 'Duarte', 'Biologia', 'Ciências Biológicas');
CALL InserirAluno('Leonardo', 'Freitas', 'Medicina', 'Ciências da Saúde');
CALL InserirAluno('Sofia', 'Castro', 'Enfermagem', 'Ciências da Saúde');
CALL InserirAluno('Daniel', 'Moraes', 'Direito', 'Ciências Humanas');
CALL InserirAluno('Luana', 'Ramos', 'Psicologia', 'Ciências Humanas');
CALL InserirAluno('Marcelo', 'Pinto', 'História', 'Ciências Humanas');
CALL InserirAluno('Renata', 'Gomes', 'Geografia', 'Ciências Humanas');
CALL InserirAluno('Alexandre', 'Sousa', 'Engenharia Civil', 'Engenharia');
CALL InserirAluno('Carolina', 'Lopes', 'Engenharia Mecânica', 'Engenharia');
CALL InserirAluno('Vitor', 'Nascimento', 'Engenharia Elétrica', 'Engenharia');
CALL InserirAluno('Natália', 'Farias', 'Engenharia de Computação', 'Engenharia');
CALL InserirAluno('Henrique', 'Monteiro', 'Ciência da Computação', 'Tecnologia');
CALL InserirAluno('Paula', 'Cavalcanti', 'Sistemas de Informação', 'Tecnologia');
CALL InserirAluno('Diego', 'Campos', 'Administração', 'Negócios');
CALL InserirAluno('Letícia', 'Borges', 'Economia', 'Negócios');
CALL InserirAluno('Rogério', 'Guimarães', 'Contabilidade', 'Negócios');
CALL InserirAluno('Simone', 'Tavares', 'Marketing', 'Negócios');
CALL InserirAluno('Fábio', 'Macedo', 'Arquitetura', 'Artes');
CALL InserirAluno('Elaine', 'Xavier', 'Design Gráfico', 'Artes');
CALL InserirAluno('Otávio', 'Pacheco', 'Música', 'Artes');
CALL InserirAluno('Viviane', 'Peixoto', 'Educação Física', 'Educação');
CALL InserirAluno('Maurício', 'Neves', 'Pedagogia', 'Educação');